version: '3'
services:
  api_gateway:
    build: ./API_GATEWAY
    ports:
      - "9000:9000"
    links:
      - api_gateway_mongodb
      - kafka
    environment:
      MONGODB_URI: mongodb://api_gateway_mongodb:27017/api_gateway_db
      KAFKA_BROKER: kafka:9092

  auth:
    build: ./auth
    ports:
      - "3001:3000"
    links:
      - auth_mongodb
      - kafka
    environment:
      MONGODB_URI: mongodb://auth_mongodb:27017/auth_db
      KAFKA_BROKER: kafka:9092

  order:
    build: ./order
    ports:
      - "3002:3000"
    links:
      - order_mongodb
      - kafka
    environment:
      MONGODB_URI: mongodb://order_mongodb:27017/order_db
      KAFKA_BROKER: kafka:9092

  notification:
    build: ./notification
    ports:
      - "3003:3000"
    links:
      - notification_mongodb
      - kafka
    environment:
      MONGODB_URI: mongodb://notification_mongodb:27017/notification_db
      KAFKA_BROKER: kafka:9092

  api_gateway_mongodb:
    image: mongo:4.4
    container_name: api_gateway_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/api_gateway:/data/db

  auth_mongodb:
    image: mongo:4.4
    container_name: auth_mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./data/auth:/data/db

  order_mongodb:
    image: mongo:4.4
    container_name: order_mongodb
    ports:
      - "27019:27017"
    volumes:
      - ./data/order:/data/db

  notification_mongodb:
    image: mongo:4.4
    container_name: notification_mongodb
    ports:
      - "27020:27017"
    volumes:
      - ./data/notification:/data/db

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

networks:
  kafka-network:
