# Stage 1: Build the React.js application
FROM node:slim AS build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build



# Stage 2: Create a production-ready Nginx server
FROM nginx

# Copy the build output from the previous stage into the Nginx image
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy your Nginx configuration file (if needed)
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf



EXPOSE 80


# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

